name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install dependencies in website directory (if needed)
      - name: npm install
        run: |
          cd website
          npm install --if-present
          npm run build --if-present
      
      # Add Azure login step
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy directly to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Claude'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_XXXXXXXXXXXXX }}
          package: './website'
